---
Name: mysiteroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'research-and-resources': 'ResearchAndResourcesHolder_Controller',        
    'member': 'Member_Controller',           